export const ConfigurationTypes = {
    COMPUTER: "Computer",
    SERVER: "Server",
    MANAGED_SERVER: "Managed Server",
    CW_SC_PARTNER_SERVER: "CW SC Partner Server",
    WORKSTATION: "Workstation",
    BACKUP: "Backup",
    CLOUD: "Cloud",
    EMAIL: "Email",
    EXCHANGE: "Exchange",
    LAPTOP: "Laptop",
    LICENSE: "License",
    RENEWAL: "Renewal",
    NETWORK_SECURITY_APPLIANCE: "Network Security Appliance",
    ROUTER: "Router",
    PERIPHERAL: "Peripheral",
    PRINTER: "Printer",
    SMARTPHONE: "Smartphone",
    SSL: "Ssl",
    SWITCH: "Switch",
    TABLET: "Tablet",
    TELEPHONE: "Telephone",
    VM: "Vm",
    WEBSITE: "Website",
    WIFI: "Wifi"
};